[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "albumentations>=1.1.0",
    "gdown",
    "numpy>=1.19.5",
    "pandas>=1.3.1",
    "protobuf>=3.19.1",
    "torch>=1.10.1",
    "torchvision>=0.11.2"
]
build-backend = "setuptools.build_meta"